name: Packet-framing Merge Verification

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull') }}

jobs:
  verify:
    uses: testofthings/.github/.github/workflows/reusable-python-merge.yaml@0.1.14
    with:
      python_module_name: "packet-framing"
      use_common_library: false
      image_name: "packet-framing"
      run_integration_tests: false
      docker_build_targets: '["production", "migrate"]'
    secrets: inherit
